---
title: "Ejercicios Introduccion"
author: "Felipe Yebes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Ejercicio 1 
```{r}
heartbpm <- c(47.53, 48.27, 49.51, 51.09, 52.57, 54.30, 54.25, 54.45, 57.95, 60.92, 61.91, 77.92, 82.07, 82.95, 83.94, 86.96, 90.42, 92.93, 100.05)
metabol <- c(6.15, 6.31, 6.43, 6.78, 6.86, 6.90, 7.37, 7.41, 8.24, 9.22, 8.16, 12.61, 15.26, 13.09, 14.59, 17.35, 18.57, 19.00, 20.70)
vulture<-data.frame(heartbpm,metabol)
rm(heartbpm,metabol)
attach(vulture)
```
Dibujar plot

```{r}
plot(vulture,main="Griffon vulture",xlab="Corazon")
rg<-lm(metabol~heartbpm,vulture)
abline(rg,lwd=2,col="red")
```
Grafico de los residuos frente a valores ajustados
```{r}
plot (rg,which=1)
```
Graficos de residuos estandarizados frente a Cuartiles de los residuos

```{r}
plot (rg,which=2)
```

Dibujar la regresión de la curva sobre el ejercicio a

```{r}
#Generamos el modelo sobre bpm de segundo grado.
mod2<-lm(metabol~heartbpm+I(heartbpm^2),vulture)
x<-seq(min(heartbpm),max(heartbpm),by=2)
y<-predict(mod2,newdata=data.frame(heartbpm=x))
plot(heartbpm,metabol,ylim=c(0,30),main="Buitres",xlab="Pulsaciones por minuto",ylab="Tasa metabólica")
lines(x,y,lwd=2,col="red")
```

